baseURL = 'https://maksim125.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Blog'
theme = "PaperMod"

[params]
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  enableMermaid = true